name: Deploy Discord Bot to Azure

on:
  push:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: |
          az acr login --name feargreedbotacr

      - name: Build and push Docker image
        run: |
          docker build -t feargreedbotacr.azurecr.io/feargreedbot:${{ github.sha }} .
          docker push feargreedbotacr.azurecr.io/feargreedbot:${{ github.sha }}

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          resourceGroup: MyContainerAppResourceGroup
          containerAppName: feargreedbot
          containerAppEnvironment: feargreedbot-env
          imageToDeploy: feargreedbotacr.azurecr.io/feargreedbot:${{ github.sha }}
          targetPort: 80
          environmentVariables: |
            DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}
          location: uaenorth
